
import "../../app/globals.css";
import Navbar from "@/components/navigation/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; //

export default function DashboardLayout({ children }) {
  return (
    <div className="flex flex-col lg:flex-row h-screen lg:min-h-screen lg:max-h-screen w-screen">
      <Navbar />
      <main className="lg:w-[91%] h-full mt-14 lg:mt-0">{children}</main>
    </div>
  );
}
