
import SysNavbar from "@/components/navigation/SysNavbar";
import "../../app/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; //

export default function DashboardLayout({ children }) {
  return (
    <div className="flex min-h-screen max-h-screen w-screen">
      <SysNavbar/>
      <main className="w-[85.7%]">{children}</main>
    </div>
  );
}
